name = "cron"
main = "src/index.ts"
compatibility_date = "2025-04-01"
upload_source_maps = true

[triggers]
# Ejecuta el Worker cada 12 horas (a las 00:00 y 12:00 UTC)
crons = ["0 */12 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "d1-tracking"
database_id = "7068903d-1c8a-4d3d-9db3-d378e494e3bf"

[observability]
enabled = true